// Regenerates src/world_map_data.js. Dev-time only — never runs in the
// deployed Worker, and the dashboard doesn't fetch anything at runtime.
//
// Usage:
//   cd tools && npm install && node build_world_map_data.js
//
// Pulls country outlines from world-atlas (ISC license; Natural Earth data
// at 110m resolution, which is itself public domain), reprojects them
// equirectangular into a 960x480 viewBox, and joins them to ISO 3166-1
// alpha-2 codes/names via iso-3166-1 (MIT) so they line up with the
// `country` field Cloudflare already provides on every pageview.
//
// A handful of disputed territories (Kosovo, Somaliland, N. Cyprus as of
// this writing) don't carry an official ISO 3166-1 numeric code in this
// dataset and are silently dropped from the map — they'd still appear in
// the plain-text Countries table if Cloudflare ever reports them.

const fs = require('fs');
const path = require('path');
const topojson = require('topojson-client');
const isoAll = require('iso-3166-1').all();

const topology = require('./countries-110m.json');
// world-atlas ships this at unpkg/jsdelivr as world-atlas@2/countries-110m.json;
// re-download it if this file is missing:
//   curl -sL -o countries-110m.json https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json

const numericToAlpha2 = {};
isoAll.forEach((c) => { numericToAlpha2[c.numeric] = c.alpha2; });

const fc = topojson.feature(topology, topology.objects.countries);

const W = 960, H = 480;
function project([lon, lat]) {
  const x = (lon + 180) * (W / 360);
  const y = (90 - lat) * (H / 180);
  return [Math.round(x * 10) / 10, Math.round(y * 10) / 10];
}

function ringToPath(ring) {
  return ring.map((pt, i) => (i === 0 ? 'M' : 'L') + project(pt).join(',')).join('') + 'Z';
}

function geometryToPath(geom) {
  if (geom.type === 'Polygon') return geom.coordinates.map(ringToPath).join('');
  if (geom.type === 'MultiPolygon') return geom.coordinates.map((poly) => poly.map(ringToPath).join('')).join('');
  return '';
}

const worldPaths = {};
let matched = 0;
const unmatched = [];
fc.features.forEach((f) => {
  const numeric = String(f.id).padStart(3, '0');
  const alpha2 = numericToAlpha2[numeric];
  if (alpha2) {
    matched++;
    worldPaths[alpha2] = geometryToPath(f.geometry);
  } else {
    unmatched.push({ id: f.id, name: f.properties && f.properties.name });
  }
});

const countryNames = {};
isoAll.forEach((c) => { countryNames[c.alpha2] = c.country; });

console.log('matched:', matched, 'unmatched:', unmatched.length, unmatched);

for (const raw of [JSON.stringify(worldPaths), JSON.stringify(countryNames)]) {
  if (raw.includes('`') || raw.includes('${') || raw.toLowerCase().includes('</script')) {
    throw new Error(
      'Generated data contains a backtick, ${ or </script sequence — ' +
      'this WILL break DASHBOARD_HTML (it is itself one giant backtick template ' +
      'literal in worker.js). Do not proceed without fixing this.'
    );
  }
}

const out = `// Generated by tools/build_world_map_data.js — do not hand-edit.
// Country outlines: world-atlas (ISC), Natural Earth 110m data (public domain).
// Alpha-2 codes/names: iso-3166-1 (MIT).
export const WORLD_PATHS = ${JSON.stringify(worldPaths)};
export const COUNTRY_NAMES = ${JSON.stringify(countryNames)};
`;

fs.writeFileSync(path.join(__dirname, '..', 'src', 'world_map_data.js'), out);
console.log('Wrote ../src/world_map_data.js');
